services:
  frigate:
    container_name: frigate
    image: "blakeblackshear/frigate:0.11.1"
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - C:\Users\ander\git\Home-Assistant\frigate\config\frigate.yml:/config/config.yml
    ports:
      - 5000:5000
      - 1935:1935
    environment:
      FRIGATE_RTSP_PASSWORD: "Metalica5"
