services:
  frigate:
    container_name: frigate
    image: blakeblackshear/frigate:stable-amd64
    restart: always
    volumes:
      - /home/homeassistant/frigate/frigate.yml:frigate.yml
      - /etc/localtime:/etc/localtime
    ports:
      - 5000:5000
      - 1935:1935
    environment:
      FRIGATE_RTSP_PASSWORD: "Metalica5"
